language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: "jazsingh05-github"
    token:
      secure: "aa2b48a9b8327b6141e0d060119e9b9f5d93734a"
jdk:
  - oraclejdk8
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
